### ISSUE TITLE
'run' page should be a nav child of its flow

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#109]
There is no way back from the run page to the flow page, add a direct link as well as the crumb hierarchy

**Comment by keevan** [comment]
Just to clarify, the flow page you are mentioning is currently located at `/admin/tool/dataflows/steps.php?dataflowid=1`

Also, do you think instead of steps.php it should just be (renamed to) details and be a generic details page for the flow itself? It's definitely doing more than just showing steps at this stage.

**Comment by brendanheywood** [comment]
+1 yes I was going to make another issue for that, it 

/admin/tool/dataflows/steps.php?dataflowid=1

should be more like:

/admin/tool/dataflows/view.php?id=1

**Comment by brendanheywood** [comment]
view.php ~= details.php not too fussed either way, view.php is more moodley but whateves
