### ISSUE TITLE
Step specific configurations need to be validated.

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#118]
Step type classes have a `validate_config()` method which needs to be called at some point.
Flows should not be able to run if the steps do not have valid configurations.
Some means of communicating invalid steps to the user needs to be implemented.

**Comment by keevan** [comment]
Entry point: https://github.com/catalyst/moodle-tool_dataflows/blob/cea95f4/classes/dataflow.php#L206

- [ ] Should do basic yaml validity checks
- [ ] Should go into the step's type class and validate it based on its own set of requirements.

**Comment by keevan** [comment]
Floating idea that steps should be able to configure their required and optional fields, and all the required ones should be displayed and loaded when choosing the step type, such that the user can see and fill them in as required.

**Comment by brendanheywood** [comment]
At the moment we create steps and choose what type it is after that, but we need to swap this so that the choice of step if the very first thing that happens. Each step will define it's own standard moodle form bits and validation, and once a step has been made its type cannot change. This will be roughly the same kind of pattern that you get for modules or blocks. The persistence is still handled centrally.

In theory a step could have invalid config, but if you tried to edit it then it would (in future) fail form validation until you got it right. So not sure about the overlap between step validation and the steps forms validation, hopefully they can be one and the same mostly.

**Comment by brendanheywood** [comment]
See also #123
