### ISSUE TITLE
Prod ready curl step

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#167]
If it is easier then break this up into discrete commits / prs, in roughly this order / groups:

group 1

* [x] should have no flow inputs or outputs
* [x] optional connectors in or out, it could be the start and download a file, or the end where it uploads one
* [x] has config for the url to curl
* [x] has config for the file to download it to, if not present discards output

group 2

* [x] mvp is if the response is 40x or 50x then send an abort to the execution manager. later improve this
* [x] has config textarea for headers, raw key: value roughly exactly as it goes over the wire. can contain expressions

group 3 

* [x] has config for the get / post / put method
* [x] has config for a text area which is raw post data
* [x] has a config checkbox which specifies if this has side effects. If it is post or put then it overrides this and will have side effects

group 4

* [x] after it executes populates variables with:
* [x] the http error code and http response eg '404' and 'content not found'
* [x] a variable with the time it took to connect and download
* [x] a variable with the bytes sent
* [x] logs errors like ssl errors or timeouts

**Comment by marcghaly** [comment]
Hi @brendanheywood,

I have not clearly understood what you meant on unchecked point `mvp is if the response is 40x or 50x then send an abort to the execution manager. later improve this`, also should there be a specific timeout for curl call ?

Concerning file download, should it be same step or another one and what should be the download location ?

https://github.com/catalyst/moodle-tool_dataflows/commit/f7321a60181a4d86e16be92199411d71afca6189#diff-cf8d12918f4729abaeec73d8b5c28ddb1d00c306ee84d79ce193c5ea0dc8308aR114

Regards,

Marc

**Comment by keevan** [comment]
Hi @marcghaly, regarding the later point of file download. I believe the _download_ behaviour should be in the same step. The download location could be configurable or fixed. But it would be ideal to work out of the scratch directory mentioned here https://github.com/catalyst/moodle-tool_dataflows/issues/158 . I think fixing it initially might make the intentions clearer when working with the dataflow at least initially.

There would then be another reader step that lets this data _flow_ across into other flow steps (if it's an array of data). If it's a file download that's not iterable (e.g. a picture) another connector step can handle it.

Not sure if this was mentioned but if the cURL request was to GET e.g. user information so it's data for a single record in JSON format, then perhaps instead of an output path (to avoid file io), it could store the response in the step as an instance variable (instead of discarded), and can be referenced by other steps later if needed using an expression.

**Comment by brendanheywood** [comment]
@marcghaly can you please always push your code into a pr to make it easier to to review

1) "mvp is if the response is 40x or 50x then send an abort to the execution manager" what I mean is that right now, if the curl fails then we should abort the entire workflow. Later in another issue we may need to improve this so that we could have more fine grained control over this, like maybe if it 50x's then we can retry it, or we actually expect a 50x in some cases so it should continue. But cross that bridge when we get to it.

2) Lets make the download path another config item. At this stage make it a fully qualified path but we will improve this later in #158 but not here.

3) yes timeout is good, make that another config item please, default can be fairly high like 1 minute. If the timeout is exceeded then abort the whole workflow

4) this needs to accept an output flow, eg download csv, then a step turns csv into flow

$outputflows = [0, 1];  <-- 

5) do not use raw curl, curl_init please use the new curl() object

**Comment by brendanheywood** [comment]
Also what is rawkey?
