### ISSUE TITLE
Create a source base object

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#26]
Sources are steps, they just don't have a 0 number of inputs

All sources will have test data config
All sources with have UI to load data from their real source and save a subset into their test data

**Comment by keevan** [comment]
Thoughts, would it be preferable to configure a source once and use it for loading data (get) and storing data (put), depending on how the user wants to move the data, rather than having a source object, and potentially a destination object with mostly the same connection handling / setup etc? Might be something worth considering down the track depending on how this evolves.

**Comment by brendanheywood** [comment]
I think what you want is related to something I thought I had on the list but now can't find, ie a workflow can have vars configures by the admin in global scope and multiple steps can pull in those vars to reuse them - eg a db connections or api keys etc. And these vars can also be set in config.php and so hidden from the admin but still usable
