### ISSUE TITLE
Tidy up var names

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#408]
Current state:
![image](https://user-images.githubusercontent.com/187449/182532811-88dc26c2-59a1-4856-a71b-4e191eda2c3d.png)

Proposing:
* [ ] env.DATAFLOW_RUN_NAME -> dataflow.run.name
* [ ] env.DATAFLOW_RUN_ID -> dataflow.run.id
* [ ] env.DATAFLOW_ID -> dataflow.id

Open to more feedback

**Comment by keevan** [comment]
Some background: 
env was initially meant to be a place to slot in global vars, and vars that the engine level knew about that might not exactly fall under something like dataflows. This was added in the style likened to other workflow engines (e.g. https://docs.github.com/en/actions/learn-github-actions/environment-variables) and potentially could be a place where variables were set, shared, etc. That said, it hasn't needed to happen.. yet? 

I'm okay with those proposed changes, as there are no real negative impacts I'm aware of. It does mean certain things the user might be interested in? Are nested a bit further down, but it's still available so it's not the worst thing.

I wonder if `run` should be under dataflows, or as a separate high level node? Similar to how steps were split out from dataflows (technically, it would have otherwise been `dataflows.steps.etc`

**Comment by jaypha** [comment]
Perhaps change `dataflow.config` to `dataflow.vars` to be consistent with `global.vars`

**Comment by brendanheywood** [comment]
> I wonder if run should be under dataflows, or as a separate high level node? 

I had the same though but mostly I was thinking that you should in theory rarely need it. The main use case I can think of is success / failure email steps at the end of a flow and you want to say which instance broke and link to it. On that topic we should make a url deep link a var to make that easier (see https://github.com/catalyst/moodle-tool_dataflows/issues/410)

I'm not fussed either way if there is a technical reason to make it a top level object.


> Perhaps change `dataflow.config` to `dataflow.vars` to be consistent with `global.vars`

+1 for this
