### ISSUE TITLE
null expressions bug should evaluate to null

### ISSUE THREAD

**Issue by marcghaly** [catalyst/moodle-tool_dataflows#415]
When an expression does not evaluate,
![Screenshot from 2022-08-03 13-30-03](https://user-images.githubusercontent.com/76186988/182672925-31a007de-595e-4107-b3e6-202ddd71d61e.png)
 the `prepare_outputs` method returns the litteral expression which leads to the following log

**Comment by keevan** [comment]
Ah but the expression didn't evaluate to null did it? 

For example if you put in something like `$result = $parser->evaluate('${{field}}', ['field' => null]);`, will it return the expression? Or will it return null?

I think this is more so when you're trying to reference a field that doesn't exist, and you're expecting it to be filled with some default value - most commonly null. 

Whilst this might work for most things it feels technically wrong. It should just fail like it does in your screenshot if the value was not found.

**Comment by brendanheywood** [comment]
@marcghaly can you try and always put a use case in here rather than just the technical bug. I see this one as a critical top of the queue bug.

Lets say you have a json file you are parsing into a flow:

```json
{"id":1, "name": "bob", "friends": "jim"}
{"id":2, "name": "jim", "friends": "sally"}
{"id":3, "name": "sally"}
```
The expression `${{record.friends}}` evaluates to 'jim' and then 'sally' for the first 2 records but for sally doesn't evaluate and the value ends up as the literal string `${{record.friends}}`. It is kinda lying to you and saying that this is the data it saw:

```json
{"id":1, "name": "bob", "friends": "jim"}
{"id":2, "name": "jim", "friends": "sally"}
{"id":3, "name": "sally", "friends": "${{record.friends}}"}
```

No matter what this is a bug. The evaluation engine might be asked to do different things in different contexts, but the main 2 things I would expect it to do is: a) if cannot evaluate it, so the expression value is empty string. ie treat it similar to the Null-safe Operator, OR b) it would throw an exception or something, eg if it was an expression for the url to use for curl then we must evaluate to a value that is shaped like a url. 

We can't have the code for the expression leaking in some cases.

https://symfony.com/doc/current/components/expression_language/syntax.html#null-safe-operator

In this specific case because we are dealing with random unknown data from outside I think it is better to nullify it rather than error out.

As an aside we need to be extremely careful when fixing issues like this that we don't inadvertently allow expressions that are inside data to get evaluated as this is essentially a Remote Code Execution vulnerability.

**Comment by brendanheywood** [comment]
If we take the example of the curl expression for the url, this could be a literal string of a url or it could be an expression like ${{global.var.someurl}}. Lets assume that didn't exist, in this case there are two ways the curl step could handle it:

1) it evaluates the expression which throws an error because it doesn't exist, it catches that and turns that into a curl specific error and handles it how it wants to
2) it evaluates the expression which automatically null coalesces it and we end up with an empty string, then it validated that as a url shaped string which would fail, continue same as before

So I guess the question is: are there any concrete use cases where returning an empty string is definitely doing to cause issues? Or should it be case by case each time we call the expression engine?

**Comment by brendanheywood** [comment]
Also a small technical chink, there is an argument we could push this complexity on the flow author (which I don't like) ie they should author the expressions using the null coalescing operator. But I don't think this work when arrays are involved, ie:

```
${{results.parent.child }}
vs
${{results?.parent?.child }}
```

```
${{results[0]['id'] }}
vs
???
```

**Comment by jaypha** [comment]
This sounds like a validation problem. Can variables get dynamically created?

**Comment by brendanheywood** [comment]
This isn't a validation problem, the expression is perfectly valid. Yes variables can be dynamically created. Pretty well every reader step json, curl etc will load stuff into a variable in the unknown shape.

**Comment by keevan** [comment]
I believe the expressions should either be there when expected, or throw an exception. 

Yes you should use the null safe operator if you are OK with the value _not_ being there (and sometimes, it really isn't available).

For your curl step example, I would agree with point 1 in which it expects a value, but it couldn't be resolved to one. Point 2 where it _validates the value anyways_, should probably be there to some degree anyways, but it depends how thorough the step author wants the validation (which happens for all values not just ones from configuration) to happen during run time.

>  So I guess the question is: are there any concrete use cases where returning an empty string is definitely doing to cause issues? Or should it be case by case each time we call the expression engine?

Not if you are explicitly defining that an empty string is an okay value to pass around. Let's say that an empty string **will** cause issues. I would want to know that it was an issue because the expression couldn't be evaluated at this particular step (as part of some step output), rather than it showing up as an issue N steps later and e.g. the curl step tried to GET an empty url.

**Comment by keevan** [comment]
With that in mind, and as part of the problem in the initial description. I believe all step outputs should be evaluated to some actual by the time it is processed, otherwise it should throw an exception.

**Comment by brendanheywood** [comment]
Ok if we got the hardball route of always throwing an exception, then we will need to put in a bit of effort into all of the places where this can happen to catch that ad turn it into a useful error.

eg in the case step if the config was:
```
first: ${{record.parent.child}}
second: blah
```
then when the fist expression explodes when parent is null then it should give you a good error message saying 'hey this doesn't exist, maybe you should use the null coalescing operator like this ....'

The problem is I can see this causing a lot of complexity to be pushed onto the flow author and it doesn't help them. And a lot of these issues are only going to arise in production when the data for whatever reason comes in a slightly different shape and so the whole thing explodes.

I think it needs to be context dependent, ie the case step would pass in a flag to the expression engine saying it wants empty strings instead of exceptions. In most other cases it could be an exception

**Comment by brendanheywood** [comment]
There will likely be a few angles of attack on this one, first up to solve the immediate problem we'll implement a count() expression function:

https://github.com/catalyst/moodle-tool_dataflows/issues/413

**Comment by brendanheywood** [comment]
Ok so just following up so this has a clear action.

IF we decide that we will always throw an exception, does this mean that parser->evaluate and parser->evaluate_or_fail should be merged? If so I'd make the first one do what the second on is doing and then remove the _or_fail version.

**Comment by keevan** [comment]
With regards to this sometimes you have multiple expressions that don't get evaluated within configuration until later. Causing it to fail as it's evaluating is probably not what you want. Unless you can guarantee the order in which you need things.

For example if you have something like:
```
max: ${{ somefield + 10}}
somefield: ${{ anotherstep.config }} 
```
It might try and eval the max field first, and might end up doing this on the first pass:
```
max: ${{ anotherstep.config + 10}}
somefield: ${{ anotherstep.config }} 
```
then
```
max: ${{ anotherstep.config + 10}}
somefield: 20
```
then finally
```
max: 30
somefield: 20
```

If there was another field linking to max, it would wait until the Nth iteration for it to become good for evaluation

If we knew ahead of time somefield needed to be evaluated first we might have been able to skip the max fields first evaluation, but it might not be possible without first trying. I believe we need a method where it fails if it doesn't eval to a non expression, and a method where it will.

**Comment by brendanheywood** [comment]
Do you have any other examples? That one above doesn't sound right to me. I agree that it should work that way but that seems to me to be an internal thing and shouldn't affect the public api. our parser->eval() call should fail if by the end of the internal loop there are still unresolved expressions, but if there are some interim unresolved ones then that is completely internal to eval()

I can imaging some examples where you have two fields and they both reference each other am happy to simply not support that use case

**Comment by keevan** [comment]
Uh sure.

3 steps in order
1. reader
2. writer `streamname: ${{ record.filename }}`
3. writer2 `streamname: ${{ steps.writer.streamname }}`

When reader is loaded/run, all the available variables from other steps, etc. are prepared. This would mean `writer2`'s stream name which points to writer's streamname value will not be resolved. To avoid this, we'd need to incorporate the DAG and not attempt to resolve any "future step" values when preparing the available variables - which is probably a good thing to do at some point anyways), but it would mean in the meantime that writer3's stream name will be unresolved.

It also means things like "record" values will stay unresolved (e.g. for writer), and should not throw an error during the reader step.

**Comment by brendanheywood** [comment]
Ok gotcha. Agree about the dag stuff and that's been on my mind too but it's all a bit much to chew off right now.

Ok so more or less what I'm hearing is this is a simple 'do nothing'
