### ISSUE TITLE
Bug Exceptions when creating new steps not being caught correctly / web service validation error function name

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_dataflows#486]
A specific case:
1) create a new web service step
2) choose a bad web service name like 'test'
3) choose a valid user
4) Try to save the step

This incorrectly does not fail with a form validation error it returns to the flow page with this error:

Coding error detected, it must be fixed by a programmer: Unexpected property 'mform_isexpanded_id_step' requested.

I have seen a few examples of this kinda of error in different places, I'm not sure if we can put in a more general form of protection? It is a little annoying as if you go back in your browser you don't even get the stuff you filled in, it is just gone

**Comment by keevan** [comment]
+1 This has been annoying, in particular I think there is some initial form validation happening, and then the step type validation happening afterwards, but that later validation is:
- happening too late, and so you're thrown into a state where you've saved the data and the flow is invalid
- or it's invalid by the time it reaches the other validation, and so it cannot save, but you're no longer on the form page so you have to re-enter the information

We just need to be mindful that sometimes, it's okay for it to be saved where the step itself might be okay, but in terms of the whole dataflow it is invalid, probably because you need to jump into another step to fix it (e.g. dependencies) or other bits.

**Comment by jaypha** [comment]
The form has changed for web service, so I cannot reproduce this bug.

**Comment by brendanheywood** [comment]
Easy
