### ISSUE TITLE
Variables code needs to be refactored

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_dataflows#614]
There are several issues with the variables code.

- It is distributed amongst several classes, sharing codespace with code that does other things.
- There is repetition of code fragments that do the same thing. (E.g dataflows::variables() and step_form::get_available_references() both construct the step->vars subtree).
- There is unnecessary execution. (E.g. step::get_export_data() is called at least twice for each step).
- There is a mixture of objects and associative arrays to store structures, causing confusion.
- It is causing performance issues in field installations.

The code should be refactored to have a separate set of classes to handle variables, including the structure and expression substitution.

**Comment by jaypha** [comment]
A branch containing an experimental alternative is available at https://github.com/catalyst/moodle-tool_dataflows/tree/614-experimental-alternative.
It is non-functional, but should give an idea of what I had in mind.

**Comment by keevan** [comment]
Some more concerns which may or may not be easily resolved:
- parser usage in various step types (using `$this->get_config()` might do what you need out of the box). 
- needing to evaluate the whole variable tree and all its expressions regardless of complexity, nesting or other. It would be nice if there was a way to simply specify what you need, and get it and only it. This might actually eliminate a lot of the performance concerns since you don't need to build the whole tree.
- nested expressions
- undefined property warning/notices for `fields.that.might.be.really.deep.or.not.exist.yet`. Handling this in a class might allow us to handle this more gracefully.
